# Language: 'en' (English) or 'pt' (PortuguÃªs)
language: en

god-on-login: true
auto-fly-enabled: true

god-groups:
  - "own"
  - "owner"
  - "adm"
  - "admin"
  - "administrator"
  - "administrador"
  - "mod"
  - "moderator"
  - "moderador"

god-players:
  - "ExamplePlayer"
